Vagrant.configure("2") do |config|
    config.vm.define "box" do |box|
            box.vm.box = "generic/ubuntu1804"
            box.vm.hostname = "ubuntu-1804-64"

            box.vm.provider:virtualbox do |vb|
                vb.name = "ubuntu-1804-64"
                vb.memory = 512
            end
            box.vm.provider:libvirt do |lv|
                lv.memory = 512
            end
            box.vm.provider:hyperv do |hv|
                hv.memory = 512
            end

    config.vm.synced_folder ".", "/vagrant"

    config.vm.provision "shell", inline:
           "sudo apt-get update -y"
    config.vm.provision "shell", inline:
            "sudo apt install -y python3-pip gdb gcc-multilib"
    config.vm.provision "shell", inline:
            "pip3 install capstone"
        end
    end
    
