Vagrant.configure("2") do |config|
    config.vm.define "box" do |box|
            box.vm.box = "generic/ubuntu1804"
            box.vm.hostname = "ubuntu-1804-64"
            box.vm.provider "virtualbox" do |virtualbox|
                virtualbox.name = "ubuntu-1804-64"
            end
    config.vm.provision "shell", inline:
            "sudo apt-get update -y"
    config.vm.provision "shell", inline:
            "sudo apt install -y python3-pip gdb gcc-multilib"
    config.vm.provision "shell", inline:
            "pip3 install capstone"
        end
    end
    